name: Check pull request description
branding:
  icon: book-open
  color: green
runs:
  using: node16
  main: dist/index.js
inputs:
  checklistItems:
    description: List of newline separated check list items that should be checked our struck out, e.g. `DCO added to all commits`
    required: true