name: Check pull request description checklist
description: Reads pull request body and makes sure that items are checked or struck out to make reading descriptions easier for maintainers and contributors.
branding:
  icon: book-open
  color: green
runs:
  using: node16
  main: dist/index.js
inputs:
  checklist-items:
    description: List of newline separated check list items that should be checked our struck out, e.g. `DCO added to all commits`
    required: true